# generated from ament_package/template/package_level/local_setup.sh.in
# OmniHand ROS2 Node Package - local_setup.sh
# Generated by build_platform_release.sh

# since this file is sourced use either the provided AMENT_CURRENT_PREFIX
# or fall back to the destination set at configure time
: ${AMENT_CURRENT_PREFIX:="/home/agiuser/code/omnihand2025/release/linux/x64/ros2/humble"}
if [ ! -d "$AMENT_CURRENT_PREFIX" ]; then
  if [ -z "$COLCON_CURRENT_PREFIX" ]; then
    echo "The compile time prefix path '$AMENT_CURRENT_PREFIX' doesn't "       "exist. Consider sourcing a different extension than '.sh'." 1>&2
  else
    AMENT_CURRENT_PREFIX="$COLCON_CURRENT_PREFIX"
  fi
fi

# function to append values to environment variables
# using colons as separators and avoiding leading separators
ament_append_value() {
  # arguments
  _listname="$1"
  _value="$2"
  # check if list is set
  eval _values=\"\$$_listname\"
  # check if value is already in the list
  case ":$_values:" in
    *":$_value:"*) : ;; # already in
    *)
      # append value to list
      eval export $_listname=\"\$$_listname:$_value\"
    ;;
  esac
}

# append to AMENT_PREFIX_PATH
ament_append_value AMENT_PREFIX_PATH "$AMENT_CURRENT_PREFIX"

# append to CMAKE_PREFIX_PATH
ament_append_value CMAKE_PREFIX_PATH "$AMENT_CURRENT_PREFIX"

# append to LD_LIBRARY_PATH
ament_append_value LD_LIBRARY_PATH "$AMENT_CURRENT_PREFIX/lib/omnihand_node"

# append to PATH
ament_append_value PATH "$AMENT_CURRENT_PREFIX/lib/omnihand_node"
