# generated from ament_package/template/package_level/local_setup.sh.in
# Omnihand2025 Node Messages Package - local_setup.sh
# Generated by build_platform_release.sh

: ${AMENT_CURRENT_PREFIX:="/home/agiuser/code/omnihand2025/release/linux/x64/ros2/humble"}
ament_append_value() {
  _listname="$1"
  _value="$2"
  eval _values=\"\$$_listname\"
  case ":$_values:" in
    *":$_value:"*) : ;;
    *)
      eval export $_listname=\"\$$_listname:$_value\"
    ;;
  esac
}
ament_append_value AMENT_PREFIX_PATH "$AMENT_CURRENT_PREFIX"
ament_append_value CMAKE_PREFIX_PATH "$AMENT_CURRENT_PREFIX"
# Set PYTHONPATH for Python message bindings
ament_append_value PYTHONPATH "$AMENT_CURRENT_PREFIX/lib/python3.10/site-packages"
