#!/bin/bash
# OmniHand ROS2 Setup for humble
# Generated by build_platform_release.sh

# Get the directory where this script is located
_AMENT_CURRENT_PREFIX=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Set AMENT_PREFIX_PATH
export AMENT_PREFIX_PATH="$_AMENT_CURRENT_PREFIX:${AMENT_PREFIX_PATH}"

# Set CMAKE_PREFIX_PATH
export CMAKE_PREFIX_PATH="$_AMENT_CURRENT_PREFIX:${CMAKE_PREFIX_PATH}"

# Set LD_LIBRARY_PATH (include both lib and lib/omnihand_node for third-party libraries)
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$_AMENT_CURRENT_PREFIX/lib/omnihand_node:$_AMENT_CURRENT_PREFIX/lib:$_AMENT_CURRENT_PREFIX/lib/python3.10/site-packages/omnihand_2025_node_msgs:$_AMENT_CURRENT_PREFIX/lib/python3.10/site-packages/omnihand_pro_2025_node_msgs"
else
  export LD_LIBRARY_PATH="$_AMENT_CURRENT_PREFIX/lib/omnihand_node:$_AMENT_CURRENT_PREFIX/lib:$_AMENT_CURRENT_PREFIX/lib/python3.10/site-packages/omnihand_2025_node_msgs:$_AMENT_CURRENT_PREFIX/lib/python3.10/site-packages/omnihand_pro_2025_node_msgs:$LD_LIBRARY_PATH"
fi

# Set PATH
if [ -z "$PATH" ]; then
  export PATH="$_AMENT_CURRENT_PREFIX/lib/omnihand_node"
else
  export PATH="$_AMENT_CURRENT_PREFIX/lib/omnihand_node:$PATH"
fi

# Set PYTHONPATH
if [ -z "$PYTHONPATH" ]; then
  export PYTHONPATH="$_AMENT_CURRENT_PREFIX/lib/python3.10/site-packages"
else
  export PYTHONPATH="$_AMENT_CURRENT_PREFIX/lib/python3.10/site-packages:$PYTHONPATH"
fi

# Source package local_setup.bash files (required for ROS2 to find packages)
if [ -f "$_AMENT_CURRENT_PREFIX/share/omnihand_node/local_setup.bash" ]; then
  source "$_AMENT_CURRENT_PREFIX/share/omnihand_node/local_setup.bash"
fi

# Source message packages (source local_setup.sh to set PYTHONPATH)
if [ -f "$_AMENT_CURRENT_PREFIX/share/omnihand_2025_node_msgs/local_setup.sh" ]; then
  source "$_AMENT_CURRENT_PREFIX/share/omnihand_2025_node_msgs/local_setup.sh"
fi

if [ -f "$_AMENT_CURRENT_PREFIX/share/omnihand_pro_2025_node_msgs/local_setup.sh" ]; then
    source "$_AMENT_CURRENT_PREFIX/share/omnihand_pro_2025_node_msgs/local_setup.sh"
fi

# Colcon workspace overlay (e.g. hand_arm_task_runner under ./install).
# The SDK prefix above does not include install/; sourcing install/local_setup.bash alone
# may not prepend AMENT (empty hooks), so we add the colcon prefix explicitly.
_COLCON_INSTALL="$_AMENT_CURRENT_PREFIX/install"
if [ -d "$_COLCON_INSTALL/share/ament_index" ]; then
  # merged install layout
  export AMENT_PREFIX_PATH="$_COLCON_INSTALL:${AMENT_PREFIX_PATH}"
elif [ -d "$_COLCON_INSTALL/hand_arm_task_runner/share/ament_index" ]; then
  # isolated install layout (single known overlay package)
  export AMENT_PREFIX_PATH="$_COLCON_INSTALL/hand_arm_task_runner:${AMENT_PREFIX_PATH}"
fi
if [ -d "$_COLCON_INSTALL/lib/python3.10/site-packages" ]; then
  export PYTHONPATH="$_COLCON_INSTALL/lib/python3.10/site-packages:${PYTHONPATH}"
fi
unset _COLCON_INSTALL

# Unset temporary variable
unset _AMENT_CURRENT_PREFIX

echo "OmniHand ROS2 packages for humble are now available"
